import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub, } 
from 'react-icons/ai'
import { RiWhatsappFill } from 'react-icons/ri';

import Image from 'next/image';
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';

export default function Home() {
  
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : "" } >
      <Head>
        <title>Mehrab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-900 dark:text-white md:px-20 lg:px-40'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>
              DevelopedBy Mehrab 
            </h1>
            <ul className='flex items-center'>
              <li>

              <BsFillMoonStarsFill  className='cursor-pointer text-2xl'
               onClick={()=>setDarkMode(!darkMode)}/></li>
              <li><a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>

          <div className='p-10 text-center'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Mehrab Tarrar
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and Designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>Freelancer providing services for programming and design content needs. join 
            me down below and let's get cracking! </p>
          </div>

          <div className='flex text-5xl justify-center gap-16 py-3 text-gray-600 dark:text-white'>
            <a href='https://twitter.com/mehrabtarrar'>  <AiFillTwitterCircle /></a>
            <a href='https://www.linkedin.com/in/mehrab-tarrar-437a57144/'><AiFillLinkedin/> </a>
            <a href='https://www.youtube.com/mehrab145'><AiFillYoutube/> </a>
            <a href='https://github.com/mehrab786'><AiFillGithub/> </a>
            <a href="https://wa.me/0923025358412">
                  <RiWhatsappFill />
             </a>
          </div>

          <div className='relative overflow-hidden bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto md:w-96 md:h-96'>
            <Image src={deved} layout="fill"  objectFit='cover'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer </h3>
            <p className=' max-w-l mx-auto dark:text-white text-md py-2 leading-8 text-gray-800 md:text-xl'>Since the begining of my journey as a Freelance
             Designer and Developer, I've done remote work for 
             <span className='dark:text-white text-teal-500'> agencies</span> consulted for <span className='dark:text-white text-teal-500'>startup </span>
             and collaborated with talented people to create digital products for both business cosumer use 
            </p>
            <p className='max-w-l mx-auto dark:text-white text-md py-2 leading-8 text-gray-800 md:text-xl'>I offer from a wide range of services,
             including programming and teaching</p>
          </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={design} width={100} height={100} style={{margin: "auto",}}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
            <p  className='py-2 dark:text-white'>Creating elegant design suited for your needs following core  design theory</p>
            <h4>Design tools I use </h4>
            <p className='text-gray-800 py-1 dark:text-white' >Photoshop</p>
            <p className='text-gray-800 py-1 dark:text-white'>Illustrator</p>
            <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:text-white'>
            <Image src={consulting} width={100} height={100} style={{margin: "auto",}}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
            <p  className='py-2'>Creating elegant design suited for your needs following core  design theory</p>
            <h4>Design tools I use </h4>
            <p className='text-gray-800 py-1 dark:text-white' >Photoshop</p>
            <p className='text-gray-800 py-1 dark:text-white'>Illustrator</p>
            <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={code} width={100} height={100} style={{margin: "auto",}}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
            <p  className='py-2'>Creating elegant design suited for your needs following core  design theory</p>
            <h4>Design tools I use </h4>
            <p className='text-gray-800 py-1 dark:text-white' >Photoshop</p>
            <p className='text-gray-800 py-1 dark:text-white'>Illustrator</p>
            <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
          </div>
        </div>  
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Since the begining of my journey as a Freelance
             Designer and Developer, I've done remote work for 
             <span className='text-teal-500 dark:text-white'> agencies</span> consulted for <span className='text-teal-500'>startup </span>
             and collaborated with talented people to create digital products for both business cosumer use 
            </p>
            <p className='dark:text-white text-md py-2 leading-8 text-gray-800'>I offer from a wide range of services,
             including programming and teaching</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap mx-auto'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height= {'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2}className='rounded-lg object-cover' width={'100%'} height= {'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3}className='rounded-lg object-cover' width={'100%'} height= {'100%'} layout="responsive"/> 
            </div>
            
            <div className='basis-1/3 flex-1'>
              <Image src={web4}className='rounded-lg object-cover' width={'100%'} height= {'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5}className='rounded-lg object-cover'width={'100%'} height= {'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6}className='rounded-lg object-cover' width={'100%'} height= {'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
};
